name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
      runs-on: ubuntu-latest  # Use Ubuntu environment
  
      steps:
      - uses: actions/checkout@v4  # Checkout the repository
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
  
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: Run pytest
        run: pytest
        
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
